# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

author:
  twitter: haviddarvey
baseurl: ""
url: "https://rexledesma.com"

# jekyll-seo-tag
twitter:
  username: haviddarvey
  card: summary_large_image
logo: /assets/images/icons/logo.png
social:
  name: Rex Ledesma
  links:
    - https://github.com/rexledesma
    - https://twitter.com/haviddarvey
    - https://www.facebook.com/andover
    - https://www.goodreads.com/rexledesma
    - https://www.linkedin.com/in/rexledesma
    - https://www.strava.com/athletes/rexledesma
    - https://open.spotify.com/user/125062534
defaults:
  - scopes:
      path: ""
    values:
      image:
        path: /assets/images/icons/logo.png
        height: 480
        width: 480

google_analytics: UA-173158493-1

permalink: /blog/:title

# build settings
markdown: Pandoc
pandoc:
  extensions:
    - section-divs
    - from: 'markdown+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
plugins:
  - jekyll-last-modified-at
  - jekyll-minifier
  - jekyll-pandoc
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
